apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: app
spec:
  selector:
    app: flask
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31012